### ISSUE TITLE
Can you give any tips on re-coloring breeze icons?

### ISSUE THREAD

**Issue by RyanTG** [freefreeno/Ares-KDE#1]
Sorry, that's such a basic question. I'm interested in doing something like your Areeze icon set, except using my custom theme/color scheme. But I'm not sure where to start. I heard oomix is good, but I think that's only for numix themes?

**Comment by freefreeno** [comment]
oomix is limited. I dont use it but I tried it a couple times and never got the desired affect. It makes base your themes off of other themes and that is fine but I like to when I can do my own base and not really start form anything. inkscape man. it sucks and its hard to learn but it is a must. I have been trying to learn for over a year now and I have made progress but i am no where near what I wished. Just start using inkscpae and watching tutorials and stuff.

**Comment by RyanTG** [comment]
Thanks. That's helpful to know your process. I use inkscape regularly for various graphics projects. It just seems crazy to me that if I just want to edit the color of the breeze folder, for example, I need to edit [50 separate svgs](https://github.com/KDE/breeze-icons/tree/master/icons-dark/places/64) and save each one in 5-6 different sizes. I figured there must be an automated process.

**Comment by freefreeno** [comment]
Use sed.  Took me along time to figure this out on my own and believe me no one tells there secrets. All I will say is use sed. That is what led me to figure out how to do it.  When you add money into the equation people are not gonna give you info very often that like me took them a long time to figure it out. I have no training or even any computer skills before I started and I am not even close to what I want to be but if people would stop hoarding secrets and help others then more people would be doing good work but when you add $ into it then they will not tell you anything. I wish I knew people to help me with this a few basic things and I would be good but there is some things that I just dont understand. I want to make all my svg' s from scratch to make a completely authentic theme but it is hard.

**Comment by RyanTG** [comment]
Word. Thanks. I guess I wasn't aware that money is involved in ~~freedesktop~~ opendesktop icons. I haven't dug into it very carefully.

I have some friends who are sed experts who have helped me to some crazy batch things in the past. So I'll check with them.

For now I'm using [Breeze Rainbow Folders](https://store.kde.org/p/1160457/), which is pretty sweet. Matches the folder color to my custom color scheme.

**Comment by freefreeno** [comment]
Remember svg's are text files bro and learn xml language if you want to get good at svg
